name: Wayfinder3D
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py36_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.0=hd04f020_2
  - openssl=1.0.2o=h26aff7b_0
  - pip=9.0.3=py36_0
  - python=3.6.5=hc167b69_0
  - readline=7.0=hc1231fa_4
  - setuptools=39.0.1=py36_0
  - sqlite=3.22.0=h3efe00b_0
  - tk=8.6.7=h35a86e2_3
  - wheel=0.31.0=py36_0
  - xz=5.2.3=h0278029_2
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - chardet==3.0.4
    - geojson==2.3.0
    - idna==2.6
    - requests==2.18.4
    - urllib3==1.22
prefix: /anaconda/envs/Wayfinder3D

