name: Wayfinder3D
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36h342bebf_0
  - chardet=3.0.4=py36h96c241c_1
  - cryptography=2.2.2=py36h1de35cc_0
  - idna=2.6=py36h8628d0a_1
  - openssl=1.0.2o=h26aff7b_0
  - pycparser=2.18=py36h724b2fc_1
  - pyopenssl=17.5.0=py36h51e4350_0
  - pysocks=1.6.8=py36_0
  - requests=2.18.4=py36h4516966_1
  - six=1.11.0=py36h0e22d5e_1
  - urllib3=1.22=py36h68b9469_0
  - geojson=2.3.0=py_0
  - intel-openmp=2018.0.0=8
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1=hb4e282d_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2018.0.2=1
  - mkl_fft=1.0.1=py36h917ab60_0
  - mkl_random=1.0.1=py36h78cc56f_0
  - ncurses=6.0=hd04f020_2
  - numpy=1.14.2=py36ha9ae307_1
  - pip=9.0.3=py36_0
  - python=3.6.4=hc167b69_3
  - readline=7.0=hc1231fa_4
  - setuptools=39.0.1=py36_0
  - sqlite=3.22.0=h3efe00b_0
  - tk=8.6.7=h35a86e2_3
  - wheel=0.31.0=py36_0
  - xz=5.2.3=h0278029_2
  - zlib=1.2.11=hf3cbc9b_2
prefix: /anaconda/envs/wayfinder3D
